### ISSUE TITLE
Code Format

### ISSUE THREAD

**Issue by MatsAndT** [thize/xd-to-flutter#11]
When I generate code for a widget, it shod be run true a format document.

From the generate widget:
```
Stack(children:<Widget>[const Text(
      'N',
      
      style: GoogleFonts.ubuntu(
        fontSize: 76,
        fontWeight: FontWeight.bold,
        color: Color(0xffffffff),
        
        
      ),
    ),const Text(
      'P',
      
      style: GoogleFonts.ubuntu(
        fontSize: 78,
        fontWeight: FontWeight.bold,
        color: Color(0xffffffff),
        
        
      ),
    )],)
```
Should look like:
```
Stack(
    children:<Widget>[
        const Text(
            'N',
            style: GoogleFonts.ubuntu(
                fontSize: 76,
                fontWeight: FontWeight.bold,
                color: Color(0xffffffff),       
        
            ),
        ),
        const Text(
            'P',
            style: GoogleFonts.ubuntu(
                fontSize: 78,
                fontWeight: FontWeight.bold,
                color: Color(0xffffffff),
            ),
        )
    ],
)
```
Link: https://flutter.dev/docs/development/tools/formatting

I know that I can format the code in the IDE, but I think the plugin shode do it before.

**Comment by thize** [comment]
![image](https://user-images.githubusercontent.com/10541221/76723664-d64cd880-6726-11ea-9fbd-3ff139c346a8.png)
I'm doing this in the new remastered version of Plugin, In this new version the complete layout is more precise and have spaces, alignments, etc.
Will fix all opened issues and improve the plugin with shortcuts, clean code and JSDoc.

Thize

**Comment by MatsAndT** [comment]
When will this new update be available? Or is this version already released? @thize

**Comment by thize** [comment]
#16
