### ISSUE TITLE
Release (maybe automatically)

### ISSUE THREAD

**Issue by StefanLobbenmeier** [thize/xd-to-flutter#12]
In the Adobe XD plugin marketplace the version is already quite old (1.3.1 - 27. Nov 2019). Please put the latest version on the marketplace. 

Also, I am not sure if that is possible, but ideally this should be automated.

**Comment by huahaomei521** [comment]
I downloaded 2.1.0xdx from git, double-click to install it, but the image tag can't be genarate to  flutter；No error information, no response，WIN10 Enterprise,CHINA

Pay attention to wearing masks！Come on！

**Comment by geallen3106** [comment]
I agree with this issue - ran into the same problem that the Adobe XD marketplace is out of date - a lot of people may be frustrated quickly and leave

**Comment by thize** [comment]
#16
