### ISSUE TITLE
error message 'artboard not implemented yet' upon clicking on 'Generate' button

### ISSUE THREAD

**Issue by TechSens** [thize/xd-to-flutter#13]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/63184320/78527600-ee88b280-780f-11ea-8998-1aaef60441a3.png">

I've clicked on the artboard, select export widget and proceed to generate but I'm getting an error message saying that 'artboard not implemented yet' 

I've removed the plugin and reinstalled but still displaying the same error message.

**Comment by fatimahmira** [comment]
you can select only 1 item to generate that. only 1 item. select item with ctrl+select, after you see "generate successfully", and then paste on another text editor for flutter code

![image](https://user-images.githubusercontent.com/49262430/79060861-ff27a580-7cb3-11ea-837f-6c7de6486824.png)


 here is my generate code
![image](https://user-images.githubusercontent.com/49262430/79060884-50379980-7cb4-11ea-9a56-d4f0afb24e0d.png)

**Comment by thize** [comment]
Please, download the latest version of the plugin

Link: https://github.com/thize/xd-to-flutter/releases/tag/2.1.0

Att.
Thize
