### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by gun20** [thize/xd-to-flutter#14]
Hi,

I downloaded the latest version of your plugin, but i get the error: extension non compatible
I'm running Adobe XD CC 2019 v20.1.12 on Windows 10.

Thanks!

**Comment by thize** [comment]
Downloaded from release tag? 
Link: https://github.com/thize/xd-to-flutter/releases/tag/2.1.0
Adobe Xd: v28.7. please, update your Xd

**Comment by gun20** [comment]
Now it works! thanks!
