### ISSUE TITLE
plugin failed to install

### ISSUE THREAD

**Issue by uzairleo** [thize/xd-to-flutter#17]
`plugin failed to install error comming ` 
i am uzair recently i try this xd to flutter in windows but its not working for me can you plz help me how to install this xd to flutter plugin secondly one thing i have to mention that i am using adobe xd cc nowadays is that a problem o something else.

![Screenshot (969)](https://user-images.githubusercontent.com/52172428/82253466-782cb380-996a-11ea-8acf-972ca3b96933.png)

**Comment by thize** [comment]
Download the latest release here: https://github.com/thize/xd-to-flutter/releases/tag/3.0.0
