### ISSUE TITLE
Request Export Group or Multi Item

### ISSUE THREAD

**Issue by sxywalkr** [thize/xd-to-flutter#22]
Hi, 
your project is help me a lot, but it's not support generate code for export group item or multi item, since developing on xd focus on design first

**Comment by thize** [comment]
Probably you are using the latest published version (1.3.1) on Adobe Xd plugin center

But the lastest release are [3.3.0](https://github.com/thize/xd-to-flutter/releases/tag/3.3.0) which is not yet in the Adobe Xd plugin center
