### ISSUE TITLE
not support full layout? 

### ISSUE THREAD

**Issue by lordmen99** [thize/xd-to-flutter#3]
Hi, nice plugin let i say. but its cant make full ui to flutter layout? i try only few part and its cant export to file

**Comment by mcabrera1101** [comment]
I have the same question! Nice Plugin.

**Comment by mcabrera1101** [comment]
Any Preview? I loved a new release!

**Comment by mcabrera1101** [comment]
Hi, I have a question, When will the plugin be ready? I needed. Excellent plugin!

**Comment by mcabrera1101** [comment]
Hi, I have a question, When will the plugin be ready? Excellent plugin! I think we all need this great plugin. Regards!!

**Comment by thize** [comment]
When I have enough time ;) 
Now it's just me on this project, any help with PR is appreciated!

**Comment by rishi1011** [comment]
Hi, Where does the generated flutter code store on the pc? It says successfully generated, but I don't know where it is.

**Comment by thize** [comment]
#16
