### ISSUE TITLE
Feature request: Generate code for Material Design Cards

### ISSUE THREAD

**Issue by mwolnymmg** [thize/xd-to-flutter#5]
Hello,

please support exporting Google Material Design Cards to code.
It would be awesome if i could get code for this element:
<img width="404" alt="Screenshot 2020-02-06 at 15 57 14" src="https://user-images.githubusercontent.com/60745914/73948580-75490e00-48f9-11ea-801e-2f3bcb7b6bf9.png">

I would like to see a widget like this:

```
Widget build(BuildContext context) {
  return Center(
    child: Card(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          const ListTile(
            leading: Icon(Icons.album),
            title: Text(‘The Enchanted Nightingale’),
            subtitle: Text(‘Music by Julie Gable. Lyrics by Sidney Stein.’),
          ),
          ButtonBar(
            children: <Widget>[
              FlatButton(
                child: const Text(‘BUY TICKETS’),
                onPressed: () { /* ... */ },
              ),
              FlatButton(
                child: const Text(‘LISTEN’),
                onPressed: () { /* ... */ },
              ),
            ],
          ),
        ],
      ),
    ),
  );
}
```

Thank you!
Martin

**Comment by thize** [comment]
I did not understand.

**Comment by thize** [comment]
Hi Martin, I didn't understand.

Do you want me to detect that when the shadow is (EXAMPLE) 5, and border radius is 2, instead of placing Container with decoration etc, it creates only Card?

**Comment by thize** [comment]
Create features to export Material Design, Things like:
 ListTile (if detect icon with title and subtitle)
Card (if detect shadow and border equals to material card)
CheckBox (...)
etc... is out of scope but i added a new topic in the READNME (# Probably out of scope / non-goals) with this feature!
