### ISSUE TITLE
Where to find generated code

### ISSUE THREAD

**Issue by pocketcarage** [thize/xd-to-flutter#6]
I have been generating the code but i dont know where to find it

**Comment by thize** [comment]
Ctrl+V \*-\*

- Thize

**Comment by MatsAndT** [comment]
It does not work with component. Version 2.1.0

**Comment by akarsh** [comment]
@thize 
I suggest adding it to the README.md file about where the generated code is?.

Because I spent some time figuring out looking for a dart file in my mac.
Then I tried to look at the GitHub repository for explanation and could not find it in the README.md file. Then I searched in the issues.
